# Generated by Django 4.2 on 2024-02-25 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_imagem_objeto_objeto_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='imagem',
            field=models.ImageField(null=True, upload_to='locais'),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='imagem',
            field=models.ImageField(null=True, upload_to='objetos'),
        ),
    ]
